/**
 * BlockProgram — Executes a queue of commands generated by Blockly blocks.
 *
 * Command types:
 *   { throttle, steer, duration }   — drive with these values for <duration> seconds
 *   { type: '_set', throttle, steer, duration: 0 } — instant-set without waiting
 *   { type: '_forever_start' }       — marks the start of an infinite loop body
 *   { type: '_forever_loop' }        — jumps back to the _forever_start location
 */
export class BlockProgram {

	constructor() {

		this.commands = [];
		this.index = 0;
		this.elapsed = 0;
		this.running = false;
		this.active = false;
		this.foreverIndex = - 1;

		// Current output values (override manual controls when active)
		this.outputX = 0;
		this.outputZ = 0;

	}

	/**
	 * Load a generated program function.
	 * @param {string} code - JavaScript source that evaluates to a function
	 *                        receiving a `commands` array and populating it.
	 * @returns {boolean} whether loading succeeded
	 */
	load( code ) {

		const commands = [];

		try {

			const fn = eval( code );
			fn( commands );
			this.commands = commands;

		} catch ( e ) {

			console.error( 'Block program error:', e );
			return false;

		}

		return true;

	}

	start() {

		if ( this.commands.length === 0 ) return false;

		this.index = 0;
		this.elapsed = 0;
		this.foreverIndex = - 1;
		this.running = true;
		this.active = true;
		return true;

	}

	stop() {

		this.running = false;
		this.active = false;
		this.outputX = 0;
		this.outputZ = 0;

	}

	/**
	 * Tick the runner forward by dt seconds.  Will advance through
	 * zero-duration commands and markers in a single frame.
	 */
	update( dt ) {

		if ( ! this.running ) return;

		// Advance through completed commands
		while ( this.index < this.commands.length ) {

			const cmd = this.commands[ this.index ];

			// ─── Marker: forever-start ───────────────────────────
			if ( cmd.type === '_forever_start' ) {

				this.foreverIndex = this.index + 1;
				this.index ++;
				continue;

			}

			// ─── Marker: forever-loop ────────────────────────────
			if ( cmd.type === '_forever_loop' ) {

				if ( this.foreverIndex >= 0 ) {

					this.index = this.foreverIndex;
					continue;

				}

				// No foreverStart found — treat as no-op
				this.index ++;
				continue;

			}

			// ─── Instant set (no duration) ────────────────────────
			if ( cmd.type === '_set' || ( cmd.duration !== undefined && cmd.duration <= 0 ) ) {

				if ( cmd.throttle !== null ) this.outputZ = cmd.throttle;
				if ( cmd.steer !== null ) this.outputX = cmd.steer;
				this.index ++;
				continue;

			}

			// ─── Duration command ─────────────────────────────────
			if ( cmd.duration !== undefined ) {

				this.elapsed += dt;

				if ( this.elapsed >= cmd.duration ) {

					this.elapsed -= cmd.duration;

					if ( cmd.throttle !== null ) this.outputZ = cmd.throttle;
					if ( cmd.steer !== null ) this.outputX = cmd.steer;

					this.index ++;
					continue; // try to process next command in same frame

				}

				// Still executing this command
				if ( cmd.throttle !== null ) this.outputZ = cmd.throttle;
				if ( cmd.steer !== null ) this.outputX = cmd.steer;
				return;

			}

			// Unknown entry — skip
			this.index ++;

		}

		// End of commands — if a forever loop exists, restart from it
		if ( this.foreverIndex >= 0 ) {

			this.index = this.foreverIndex;
			this.elapsed = 0;
			return;

		}

		// Otherwise stop
		this.stop();

	}

}
